version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - pip install awscli --upgrade --user
      
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      
  build:
    commands:
      - docker build --tag "${$ECR_REPO_URI}:latest" .
      - docker push "${$ECR_REPO_URI}:latest"
