version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - echo install completed      

      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login)
      - echo pre_build completed
      
  build:
    commands:
      - echo Entered the build phase...

      - echo build completed      
      
  post_build:
    commands:
      - echo Entered the post_build phase...
      
      - echo post_build completed
